apiVersion: v1
kind: Service
metadata:
 name: node
 labels:
   run: node
spec:
 ports:
  #the port thet this service should serve on
 - port: 80
   targetPort: 4200
   protocol: TCP
 selector:
  run: node
 type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  selector:
    matchLabels:
        run: node
  replicas: 2
  template:
    metadata:
       labels:
         run: node
    spec:
      containers:
       - name: node
         image: omega/node-repo:latest
         ports:
           - containerPort: 4200
